### ISSUE TITLE
Unlimited oil from pump jack.

### ISSUE THREAD

**Issue by Wigalot** [Flaxbeard/ImmersivePetroleum#105]
I'm playing Modern Skyblock 3 (3.1.5.3). I'm unsure if this is an issue with the pack or the mod Immersive Petroleum. To get power going I ran the core sample drill and discovered a chunk with 6.8million mb of oil. I placed the pump jack down and connected it like this: pump jack = distillation tower = (diesel) boiler = steam turbine. I'm producing power all fine and dandy and it works but the oil from the chunk seems to be endless. After a week I ran the core sample drill again in the same chunk to check the oil levels remaining and the core sample states 'up to 6mb/tick of trace oil'. Another week later and it still says the same with no loss of power production. So are the chunks with oil in endless? Is this as intended or is this just Modern Skyblock 3 that allows this?

**Comment by Darkosto** [comment]
This is a feature of the mod. If you noticed, the amount of "trace oil" you get is extremely low compared to pumping from a chunk with oil in it.

**Comment by Wigalot** [comment]
Yes, as I stated I am aware of that. But it is endless. 'Trace' meaning a small amount left. But it never seems to end after the core sample reads '6mb/tick of trace oil'. What i'm asking is this: Is it intended for it to be an endless supply? I.E: Shouldn't it run out?

**Comment by Darkosto** [comment]
"This is a feature of the mod."

No, it does not run out it's meant to continuously give oil very much like Factorio does not run out but gives small amounts once the reservoir is empty.

**Comment by Flaxbeard** [comment]
As Darkosto said, when a reservoir is depleted, by default, it will still provide oil at a lower mB/tick rate. This is, of course, configurable to have truly finite oil.
