### ISSUE TITLE
Promblems with multiblocks in the newest IE version

### ISSUE THREAD

**Issue by ghost** [Flaxbeard/ImmersivePetroleum#106]
since the latest version of IE some things about multiblocks changed and many any multiblockstructure that has an gui seems to be broken they still look the same but the gui wont open if right clicked and they also seem to have lost every funtionality (pumpjack still works sine it has no gui)

IE:0.12-80
IP:1.1.8

**Comment by justinrusso** [comment]
Having this same issue as well. Did IE change something that broke all the addon mods?

**Comment by Flaxbeard** [comment]
IE did change something that broke IP - fix coming very soon

**Comment by Flaxbeard** [comment]
Update out
