### ISSUE TITLE
Immersive Petroleum Distillation Tower Miscount for Steel Scaffolding Slab

### ISSUE THREAD

**Issue by Fireztonez** [Flaxbeard/ImmersivePetroleum#108]
Hello,
On the Immersive Manual, the Immersive Petroleum Distillation Tower have miscount for Steel Scaffolding Slab. The manual said needed 33 Steel Scaffolding Slab, but only 30 is needed for the construction.

Problem found in SevTech 3.0.4
Immersive Petroleum 1.1.9

https://github.com/Darkosto/SevTech-Ages/issues/1526
Fireztonez

**Comment by darthvader45** [comment]
Seems that issue you referenced is closed now.  Should the issue here be closed @Flaxbeard?
