### ISSUE TITLE
[Bug]Reservoir Biome Whitelist/Blacklist does not appear to work

### ISSUE THREAD

**Issue by Mike-U5** [Flaxbeard/ImmersivePetroleum#111]
Or maybe I'm just stupid. But I have this in my config file
```
        S:reservoirs <
            aquifer, water, 5000000, 10000000, 6, 30, [], [0], [], []
            oil, oil, 4000000, 10000000, 0, 40, [], [], [OCEAN], []
            Rich Oil Reservoir, oil, 10000001, 12000000, 6, 40, [], [], [], [OCEAN]
            lava, lava, 250000, 1000000, 0, 30, [1], [], [OCEAN], []
         >
```
Expectation: Regular oil and lava does not show up in Ocean Biomes. "Rich Oil" shows up exclusively in Ocean biomes.

What actually happened: Regular oil and lava reservoirs still generate in ocean biomes, and I haven't seen a rich oil reservoir so far and I looked around quite a bit, altough that **could** be a case of bad RNG.

The book also says _"Rich Oil Reservoir only generates in ."_ which indicates that something is wrong.

**Comment by MusicMaestro123** [comment]
I believe you put OCEAN in the wrong square brackets for the Rich Oil Reservoir.

**Comment by MusicMaestro123** [comment]
Or it's the other way round?
