### ISSUE TITLE
Fluids are WAYYYY to hot

### ISSUE THREAD

**Issue by tyler489** [Flaxbeard/ImmersivePetroleum#123]
Gasoline and Diesel both temp out at 3900 Degrees... this is WAY to hot for them  https://gyazo.com/fc1e57fc2c66e68782b635d351e8b8ff

**Comment by Flaxbeard** [comment]
IP doesn't set fluid temperatures, they should be the default (300)

**Comment by Flaxbeard** [comment]
Feel free to re-open if this seems unique to IP. I would guess that this might be another mod interacting poorly
