### ISSUE TITLE
Having issue with Immersive Petroleum in a mod pack.

### ISSUE THREAD

**Issue by ghost** [Flaxbeard/ImmersivePetroleum#140]
I've been making a mod pack and am having issues with Immersive Petroleum. I can't tell if it is an issue with Immersive Petroleum specifically or some other mod causing a conflict. It seems to be throwing some kind of error about loading models but I'm not too familiar with Java so that is a guess on my part. I'm posting a log here in case it is an issue with Immersive Petroleum and if it isn't an issue with this mod I would appreciate being pointed towards what mod is causing the issue.

[The Log](https://pastebin.com/vKqGV6hX)

**Comment by ThePoshTux** [comment]
Any updates on this? The log Pastebin has expired so myself or others can't see the issue.

**Comment by ghost** [comment]
I stopped developing the mod-pack that was causing the issue, so I no longer have anyway of reproducing the bug. Might as well just close the issue for now.

**Comment by Flaxbeard** [comment]
Closing for now, feel free to re-open
