### ISSUE TITLE
[Bottling Machine] Does not place projections correctly

### ISSUE THREAD

**Issue by UnlimatedStone9** [Flaxbeard/ImmersivePetroleum#141]
The bottling machine projector does not project the bottling machine correctly, it instead places the conveyor belts facing the opposite direction, this can be confusing when attempting to quickly place and construct the machine

**Comment by ThePoshTux** [comment]
It is projecting them correctly. The machine can be assembled in either direction. Use sneak + pick block (shift + middle mouse by default) to mirror the blueprint into the correct direction.

**Comment by UnlimatedStone9** [comment]
Good to know, Thanks for letting me know about this! I just wasn't aware.

**Comment by Flaxbeard** [comment]
Looks like this is a non-issue, so closing for now
