### ISSUE TITLE
[1.12.2] Biome whitelist doesn't generate

### ISSUE THREAD

**Issue by specklogan** [Flaxbeard/ImmersivePetroleum#149]
Immersive Petroleum 1.1.9, Immersive Engineering 0.12.89

Trying to whitelist which biomes it can spawn in, yet doesnt generate and in the book it gives me this> https://gyazo.com/97823c58e9fedde88824663e34a17a9e

Heres my config, 

 # List of reservoir types. Format: name, fluid_name, min_mb_fluid, max_mb_fluid, mb_per_tick_replenish, weight, [dim_blacklist], [dim_whitelist], [biome_dict_blacklist], [biome_dict_whitelist]
        S:reservoirs <
            aquifer, water, 5000000, 10000000, 6, 30, [], [0], [], []
            oil, oil, 2500000, 15000000, 6, 40, [1], [], [], [OCEAN,SANDY,SWAMP,MESA]
            lava, lava, 250000, 1000000, 0, 30, [1], [], [], []

**Comment by specklogan** [comment]
No help?

**Comment by Andrey-007** [comment]
> Иммерсив Петролеум 1.1.9, Иммерсив Инжиниринг 0.12.89
> 
> Попытка внести в белый список, какие биомы он может породить, но не генерирует, и в книге он дает мне это> https://gyazo.com/97823c58e9fedde88824663e34a17a9e
> 
> Вот мой конфиг,
> 
> # Список типов резервуаров. Формат: имя, псевдоним, min_mb_fluid, max_mb_fluid, mb_per_tick_replenish, вес, [dim_blacklist], [dim_whitelist], [biome_dict_blacklist], [biome_dict_whitelist]
> ```
>     S:reservoirs <
>         aquifer, water, 5000000, 10000000, 6, 30, [], [0], [], []
>         oil, oil, 2500000, 15000000, 6, 40, [1], [], [], [OCEAN,SANDY,SWAMP,MESA]
>         lava, lava, 250000, 1000000, 0, 30, [1], [], [], []
> ```
Need to use Numeric ID biome
OCEAN = 0

**Comment by Flaxbeard** [comment]
07321d2 should resolve
