### ISSUE TITLE
World leak in EventHandler#toRemove

### ISSUE THREAD

**Issue by malte0811** [Flaxbeard/ImmersivePetroleum#154]
The worlds (keys) are never removed from the map. This causes a lot of log spam from Forge complaining about leaked worlds. The value lists of the map are also never cleared, which is probably a bug as well.  
A similar issue can probably happen with `napalmPositions` as well.

Noticed on the official IE server.

**Comment by Flaxbeard** [comment]
Should be resolved in next update
