### ISSUE TITLE
Crash on Stop Button [1.16.3]

### ISSUE THREAD

**Issue by curlywaffles** [Flaxbeard/ImmersivePetroleum#183]
While viewing pumpjack schematics in engineering manual. When clicking the stop button crash to desktop. Repeatable 100%

**Comment by TwistedGate** [comment]
a crash report would still be nice to have

**Comment by curlywaffles** [comment]
Crash Report:
https://pastebin.com/HbBfj0sZ

**Comment by TwistedGate** [comment]
Fixed for next release
