### ISSUE TITLE
IE Core Drill is not reporting whether or not chunk has actual fluid reservoir

### ISSUE THREAD

**Issue by Algester** [Flaxbeard/ImmersivePetroleum#184]
if it wasnt for a tip to use the debug tool to check whether or not said chunk has said fluid reservoir or not, then I wouldnt actually get started with IP, in anycase the IE core drill sample will not say how many mBs of fluid the chunk has but the debug tool will state otherwise

**Comment by Razsiel** [comment]
Using commands (specifically the command line on a server I play on) we got this possibly related error;

command ran; `/execute as <player> run ip reservoir get` (using just the player command without /execute it only spits out the latter message to the player)

`[22:27:54] [Server thread/FATAL] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/resources/I18n for invalid dist DEDICATED_SERVER
[22:27:54] [Server thread/INFO] [minecraft/DedicatedServer]: An unexpected error occurred trying to execute that command`

**Comment by TwistedGate** [comment]
Techincaly is a duplicate by now lol

Anyways it'll be fixed next release. #181
