### ISSUE TITLE
[1.16.3] Uncraftable napalm and motorboat

### ISSUE THREAD

**Issue by Pirojok3000** [Flaxbeard/ImmersivePetroleum#189]
I tried to make napalm, but the mixer does not mix gasoline and aluminum dust. Recipe is not displayed in NEI
And motorboat, it just doesn't exist in the mod.
![bug](https://user-images.githubusercontent.com/75800506/101799032-b8c56780-3b1c-11eb-8d6a-eb1d1c993f76.png)

**Comment by TwistedGate** [comment]
Forgot to add the recipe for the napalm

as for the speedboat #186

**Comment by TwistedGate** [comment]
Fixed in 3.1.0
