### ISSUE TITLE
Fluid reservoirs not appearing in core samples, or very rarely

### ISSUE THREAD

**Issue by Crowfooted** [Flaxbeard/ImmersivePetroleum#191]
Using a custom modpack on 1.16.4, all the other features of IE and IP seem to be working as intended, but after sampling 50+ areas, I'm yet to find a single fluid reservoir. The config is default (0.5/chunk). Either they're not appearing at all in this modpack or they are extremely rare/not tied to chunks in the way described.

Couldn't replicate it with only IE and IP installed, but thought I'd open an issue anyway in case you wanted to fix potential bad mod interactions, if you can figure out which mod is interacting.

[Here](https://pastebin.com/ZUagPXS8) is a list of the mods I'm using. There are no error messages related to the problem that I can see in my logs so far. I may try to narrow it down later if I get some time, but I have only a little experience with modding so I don't really know what to look for with regard to the type of mods that might interact with IE/IP deposits.

**Comment by TwistedGate** [comment]
Sounds like #181

**Comment by Crowfooted** [comment]
Reading that thread it seems like the reason I was able to find deposits when testing with only IE and IP was because I was testing in a singleplayer world. Good to know the deposits are there even if the sampler doesn't show them. Thanks!
