### ISSUE TITLE
CurseForge source link no longer refers to active development repository

### ISSUE THREAD

**Issue by eilamg** [Flaxbeard/ImmersivePetroleum#193]
Hey @TwistedGate,

If you've fully taken over development of the mod, I'd like to request that you consider either

- Updating the source and issues links in the CurseForge page, or
- Pushing any and all changes from your fork to this repo, and publish future builds from here

As it currently stands, the only reference to the active development repository for the project anywhere on CurseForge is a single comment made by you in November.

Cheers

**Comment by TwistedGate** [comment]
Nah, im gonna move my operation to this repo _Soon™_ :D

**Comment by TwistedGate** [comment]
Changed my mind, moved over to my repo~

**Comment by TwistedGate** [comment]
ID Mishap, ignore.
