### ISSUE TITLE
Asphalt concrete recipes don't work in the IE assembler with fluid input

### ISSUE THREAD

**Issue by Limewood** [Flaxbeard/ImmersivePetroleum#197]
The two asphalt concrete recipes (with slag or sand) don't work in the Immersive Engineering Assembler, if using water as fluid input rather than buckets of water.
I fixed it in a local datapack, replacing
```
"B": {
      "item": "minecraft:water_bucket"
    }
```
with
```
"B": {
      "tag": "minecraft:water",
      "amount": 1000,
      "type": "immersiveengineering:fluid"
    }
```
in the recipe json files.
I don't know if IP uses datapack files directly or builds them from code (or something else), but I add this local fix in the hopes that it could be useful.

**Comment by TwistedGate** [comment]
Fixed in `1.6.4-3.1.0-2`
