### ISSUE TITLE
Crashing with this message "Immersive Petroleum encountered an error during the common_setup event phase"

### ISSUE THREAD

**Issue by Qattos** [Flaxbeard/ImmersivePetroleum#198]
I'm using the latest version of your mod (1.6.4-3.1.0-2) in Valhelsia 3 modpack.
And latest version of forge 35.1.13

Crash report:
https://pastebin.com/EJUASU6y

**Comment by Qattos** [comment]
Apparently your mod's version 3.1.0 [1.6.3] is working fine.
You can close this issue if you want.

**Comment by TwistedGate** [comment]
Minimum IE version is `129` for IP `1.6.4-3.1.0-2` you're using IE `128`

**Comment by Qattos** [comment]
I must have messed things up when updating the other 100 mods, thanks a lot, it's now working as intended.
