### ISSUE TITLE
[1.16.4] Cannot Extract Diesel From Distillation Tower or fuel IE Tools with It

### ISSUE THREAD

**Issue by Koku0** [Flaxbeard/ImmersivePetroleum#203]
**Forge Version:** 35.1.15
**Immersive Engineering Version:** 1.16.4-4.1.2-129
**Immersive Petroleum Version:** 1.16.4-3.1.0-2

Using buckets, I cannot extract diesel from the distillation tower using a bucket nor I can fuel IE tools (buzzsaw, mining drill) using it after it is put into a silo or any other modded fuel container.

Biodiesel can still be used to fuel the tools, and other products of the distillation tower such as gasoline can be extracted using a bucket.

**Mods Used:** Immersive Engineering, Immersive Petroleum, JEI, JER

**Comment by TwistedGate** [comment]
Reason for that is its trying to fill a bucket with less than 1000mB and failing of course.

But i'll see what i can do nontheless

**Comment by TwistedGate** [comment]
Fixed in `1.16.5-3.2.0-3`
