### ISSUE TITLE
Breaking Asphalt Concrete does not give a block

### ISSUE THREAD

**Issue by Koku0** [Flaxbeard/ImmersivePetroleum#204]
[1.16.4]
**Forge Version:** 35.1.15
**Immersive Engineering Version:** 1.16.4-4.1.2-129
**Immersive Petroleum Version:** 1.16.4-3.1.0-2

When you break an asphalt concrete block with a pickaxe or an Immersive Engineering mining drill, a block does not drop, which it should.

**Mods Used:** Immersive Engineering, Immersive Petroleum, JEI, JER

**Comment by mnsnownutt** [comment]
This is still happening in MC 1.16.5
Forge version 36.0.41
IP version 1.16.4-3.1.0-2
IE version 1.16.5-4.2.2-132

**Comment by TwistedGate** [comment]
Fixed in `1.16.5-3.2.0-3`
