### ISSUE TITLE
Japanese translation includes bad item.

### ISSUE THREAD

**Issue by koh-gh** [Flaxbeard/ImmersivePetroleum#211]
For 1.16.x, ja_jp.json has the following item.
`    "": "/linkできたら()と()内消して",`

This is an illegal item and has a lot of impact on other content.

- Impact on Packmenu
![2021-01-16_11 25 16](https://user-images.githubusercontent.com/36918206/104795009-b2e33600-57ee-11eb-90e1-53ab41e5a8e8.png)

- Impact on Tetra
![2021-01-16_11 21 56](https://user-images.githubusercontent.com/36918206/104795028-c7bfc980-57ee-11eb-9985-607487196814.png)

I am currently working on a new Japanese translation, but please remove this item as soon as possible.

**Comment by TwistedGate** [comment]
You're more than welcome to remove it since you are working on the translation file already.
it's redundant/unused anyway.

**Comment by koh-gh** [comment]
Thank you for your reply. Translation will probably take a week or more.
So, if you plan to release the new version in the near future, I would be grateful if you could update it without waiting for my PR.

**Comment by koh-gh** [comment]
Now I have sent a PR, so I close this issue.
