### ISSUE TITLE
[1.16.4] Allow Flare Stack To Burn Any IE/IP Oils

### ISSUE THREAD

**Issue by VaelophisNyx** [Flaxbeard/ImmersivePetroleum#214]
This would be a wonderful enhancement, allowing removal of excess fluids such as unwanted Creosote Oil

**Comment by TwistedGate** [comment]
I have already something planned for this, see #200

Also right now the flarestack already can burn away excess/unwanted creosote and lubricant (Should anyway)

**Comment by LeoBeliik** [comment]
as for now, it only works with lubricant and plant oil.

**Comment by TwistedGate** [comment]
Oh yeah, i got something mixed up there..

**Comment by TwistedGate** [comment]
Taken care of by 00ee3a8e34c8882f767610c20cba1ad973adbdf7 (Hopefully)
