### ISSUE TITLE
Can't connect more than 1 wire in a connector

### ISSUE THREAD

**Issue by IlDonCetriolo69** [Flaxbeard/ImmersivePetroleum#215]
hi, I wanted to try out this mod but when I try to create an eletricity grid i can't connect more than 1 wire to a connector saying "cannot connect this wire here", making it impossible to do a funcional power grid. I tried this in 1.7.10 1.10.2 1.12.2 1.16.4 and it only worked on 1.7.10. 
You will say "then play on 1.7.10" i would but i also wanted to use immersive petroleum but there's no support for 1.7.10.
Pls help i really wanted to play this mod

**Comment by mindforger** [comment]
you have to place down wire relays, connectors can only connect one wire, relays more (dunno if there is an actual limit)

be aware, relays do NOT conduct power to the block attached, so you need to go: generator - connector - wire - relay - more wires, it should be described in the ingame manual ... so obligatory RTFM :D

Edit: whoops ... you seem to have hit the wrong mod, Immersive Engineering is providing the Wire, Immpersive Petroleum "only" adds stuff to IE

**Comment by IlDonCetriolo69** [comment]
omg thank you so much my stupid a*s thougth connectors were needed to _connect_, anyway thank you again
