### ISSUE TITLE
projector doesn't lock image

### ISSUE THREAD

**Issue by Parciwal** [Flaxbeard/ImmersivePetroleum#225]
The projector works fine, but for some reason I can`t lock the Image.

https://user-images.githubusercontent.com/78496745/107091037-60030a00-6801-11eb-9b62-e91e5e0ab6e5.mp4

https://user-images.githubusercontent.com/78496745/107091076-6e512600-6801-11eb-9847-5b6054415a51.mp4

**Comment by TwistedGate** [comment]
Unable to repoduce
