### ISSUE TITLE
Setting "asphalt_speed" to false does not work (still gets more speed on asphalt)

### ISSUE THREAD

**Issue by sharlin073** [Flaxbeard/ImmersivePetroleum#229]
Setting "asphalt_speed" to false does not work (still gets more speed on asphalt)

Version : Lastest Immersive Patroleum on Forge 36.0.26

Yes, that's all.
I do not have any other mods adding asphalt.
I do have "happytrails" mod enabled, but it adds speed via potion effect, so this is not affecting, I assume.

Thank you! :)

**Comment by TwistedGate** [comment]
91f1a5c822a0b65393eea1771dcfcc28f7a651a8 this *should* fix that in the next release

**Comment by sharlin073** [comment]
Thanks!
