### ISSUE TITLE
Server config file doesn't generate

### ISSUE THREAD

**Issue by Gwolfski** [Flaxbeard/ImmersivePetroleum#231]
Forge 35.1.37 (1.16.4)
Immersive Engineering 1.16.4-4.12-129
Immersive Petroleum 3.1.0-2

Issue: The server config file for IP does not generate either in single player or multi player. Only "immersivepetroleum-common.toml" generates. As a result, I am unable to set such configs as fluid reservoir generation options. Other mods (I tested create and botania) do generate both common and server config files

How to reproduce:
Install the appropriate forge version
Install IE and IP
Generate a world
check the world's serverconfig folder and find the IE file but there is no file for IP

Notes: Singleplayer tested on Win10, Multiplayer (serverside) tested on a Linux server

**Comment by TwistedGate** [comment]
91f1a5c822a0b65393eea1771dcfcc28f7a651a8 this *should* fix that in the next release
