### ISSUE TITLE
[1.16.5] Config generates .bak copy every time the game starts up.

### ISSUE THREAD

**Issue by Gbergz** [Flaxbeard/ImmersivePetroleum#233]
### **Title ^**

In newer versions of Forge the config file for Immersive Petroleum generates a new config with the file extension ``.bak`` each time the game starts.

> Example:
![image](https://user-images.githubusercontent.com/26634554/110475139-cc16ad80-80e0-11eb-8650-99c10185fc64.png)

I know this happens/happened to other mods but got fixed after awhile, think it has to do with some recent forge changes.

Minecraft: ``1.16.5``
Forge: ``36.0.46``
Immersive Petroleum: ``3.1.0-2``

**-** Gbergz

**Comment by Rodg88** [comment]
related issue, https://github.com/NillerMedDild/Enigmatica6/issues/1396

Looks like it's generating an invalid config by default, so it keeps generating it over and over?

**Comment by TwistedGate** [comment]
Should be fixed in `1.16.5-3.2.0-3`

Keeping this open tho, just incase

**Comment by Rodg88** [comment]
Ah i didn't see the update, I'll test it

**Comment by Gbergz** [comment]
Should be fixed in the Forge version 36.0.53+
Changelog note: ``Automatically fix some issues with configurations deemed invalid for simple reasons``

Edit: Haven't received any more .bak files when updating forge.

**Comment by Rodg88** [comment]
In 3.2.0-3, it's now that serverconfig that is reloading
```[16Mar2021 01:57:42.955] [Thread-1/WARN] [net.minecraftforge.fml.config.ConfigFileTypeHandler/CONFIG]: Configuration file /Users/Rodger/My Games/GDLauncher/instances/E6 0.4/saves/World/serverconfig/immersivepetroleum-server.toml is not correct. Correcting```
But if forge is fixing it on their end, may not be a real issue

**Comment by Gbergz** [comment]
Ah yeah, actually it still does it there. Didnt notice. However the main config is fixed with the recent forge updates.

**Comment by ZephyrWindSpirit** [comment]
I'm making a note that this is still an active issue with 1.16.5-3.2.0-3, with the reloading serverconfigs. My world lags out and ends up being frozen in a constant state of 'correction'
