### ISSUE TITLE
Crashing when placing fluid tanks in distiliation tower

### ISSUE THREAD

**Issue by benbenlaw** [Flaxbeard/ImmersivePetroleum#234]
Before reporting:
crashing when placing tanks of fluids from cyclic into distilation tower

Description of the issue:
crashing when placing tanks of fluids from cyclic into distilation tower

Crashlog:
[crash-2021-03-11_08.39.41-server.txt](https://github.com/Flaxbeard/ImmersivePetroleum/files/6122052/crash-2021-03-11_08.39.41-server.txt)

Versions & Modlist
cyclic: 2.2.9
immersive: 4.2.4-134
forge: 36.0.46
minecraft:1.16.5

**Comment by TwistedGate** [comment]
Should be fixed for now in the next release (0bb580eb1b92a9a9bf4479350557e5d8cac3ad70)
