### ISSUE TITLE
1.16.5- Two pumpjacks on same pipeline system do not operate at the same time

### ISSUE THREAD

**Issue by SteelBlue8** [Flaxbeard/ImmersivePetroleum#240]
I have two pumpjacks next to each other, both connected up to the same pipeline system. Both are fully charged, facing the same direction, and located within 1 single oil chunk with no blocks leaving that chunk. Only one of the pumpjacks will only operate at any given time, despite the fact that the distillation tower has capacity for more than one pumpjack. Adding a fluid pump, both with electricity or without, did not remedy this fact.

**Comment by TwistedGate** [comment]
You most likely drained the reservoir

**Comment by SteelBlue8** [comment]
> You most likely drained the reservoir

Ah, that makes sense! Thankyou very much, and sorry for the hassle!
