### ISSUE TITLE
Failure message: Immersive Petroleum has failed to load correctly

### ISSUE THREAD

**Issue by dave75vgnut** [Flaxbeard/ImmersivePetroleum#241]
Not sure what issue is, but put crash report on : https://pastebin.com/MyQpqZLn and also fml log: https://pastebin.com/jejCGkbY

**Comment by TwistedGate** [comment]
Wrong repo.
Known issue: https://github.com/TwistedGate/ImmersivePetroleum/issues/55
Read: https://github.com/Flaxbeard/ImmersivePetroleum/issues/237
