### ISSUE TITLE
Two pump jacks on same chunk not working on server

### ISSUE THREAD

**Issue by Boyownik** [Flaxbeard/ImmersivePetroleum#25]
Like in title, i have newest version of mod. On SP it's working fine. 
Screenshots: http://imgur.com/a/gMJYN
Both of them have full energy buffer, no redstone signal (on non  inverted mode).
Edit: When i turn off one which is working, other one start working.

**Comment by Flaxbeard** [comment]
Is all the oil drained from that chunk?

**Comment by Boyownik** [comment]
Nope

**Comment by Boyownik** [comment]
Nvm! My fault, propably when i was updating mod something went wrong and all my oil on chunks shuffled :/
