### ISSUE TITLE
Distillation Tower outputs are incorrect

### ISSUE THREAD

**Issue by FSDel** [Flaxbeard/ImmersivePetroleum#26]
Version: 
ImmersiveEngineering-0.10-58
immersivepetroleum-1.10.2-1.0.4

Bitumen is being thrown to a block a little distance away from the multi-block.
Diesel output appears blank, and pipes do not connect to it.

Please see the screenshot.
http://i.imgur.com/ekqUcfW.png

**Comment by tahg** [comment]
As an addendum, this appears to be because the tower does not take into account the fact that it's mirrored.
