### ISSUE TITLE
Crash while placing schematic

### ISSUE THREAD

**Issue by Louis9902** [Flaxbeard/ImmersivePetroleum#27]
I've tied to place the schematic with shift right click and then my game froze and crashed

**Forge Version:**  13.20.0.2314
**Immersive Engineering Version:** 0.11-59-109
**Immersive Petroleum Version:** 1.11.2-1.0.5

The exception from the crash:
[Log from Line 2018](https://paste.ee/p/BH84q)

Also at the beginning there are some errors as well but noting game breaking:
[Log from Line 232](https://paste.ee/p/BH84q)

**_Mods:_**
-   antiqueatlas-1.11.2-4.4.4
-   AppleTrees-1.11.2-V2
-   ChestTransporter-1.11.2-2.7.9
-   CraftTweaker-1.11.2-3.0.25
-   disenchanter-[1.11.2]1.5
-   DynamicSurroundings-1.11.2-3.4.5.1
-   ezstorage-2.4.1-[1.11.2]
-   GiacomosFoundry-1.11.2-1.3.12
-   GoodOldBackpacks-1.1.0
-   hammerz-1.11.2-0.1.4.27
-   ImmersiveEngineering-0.11-59-109
-   immersivepetroleum-1.11.2-1.0.5
-   jei_1.11.2-4.3.6.282
-   Level Up! 2-1.0.2-1.11.2
-   MobGrindingUtils-0.2.0
-   OreExcavation-1.3.95
-   signpost-1.11.2-1.05.3
-   tanspit-1.11.2-1.3
-   ToughAsNails-1.11-2.0.5
-   Traverse-1.11.2-1.1.1-20
-   VanillaTeleporter-1.11-1.6.1
-   xpbook-1.11.2-0.0.2-beta

**Comment by Flaxbeard** [comment]
Which schematic?
