### ISSUE TITLE
Distillation Tower Problem

### ISSUE THREAD

**Issue by AngieTheDemoness** [Flaxbeard/ImmersivePetroleum#28]
The Outpout port for Diesel doesn't seem to work, and chunks without any liquid veins will display having 3mb extraction oil thingy.

**Comment by Ravalli03** [comment]
I'm having the same issue, can't output diesel from distillation tower

**Comment by KindarConrath** [comment]
I'll 3rd that, Diesel doesn't output and pumpjacks won't run if there is only "trace" oil in a chunk (I don't know about if you pump all of it out, but chunks that start with trace amounts won't pump.

**Comment by paul6334** [comment]
I'm having a similar issue. Gasoline, diesel and lubricant will not leave the distillation tower in the latest version.

**Comment by Flaxbeard** [comment]
what sort of fluid output are you using?

**Comment by paul6334** [comment]
The orange one, transported in standard I.E. pipes.

**Comment by paul6334** [comment]
I can get it to draw off to things that accept that fluid, but not to tanks.

**Comment by paul6334** [comment]
I figured it out. all of the tanks got lubricant for some reason. not a bug, just a quirk of I.E. fluid routing.

**Comment by calloatti** [comment]
Hint: use an IE fluid router at the output when using IE pipes

**Comment by paul6334** [comment]
I figured out a working system. And I think my version looks cooler.
