### ISSUE TITLE
Allow the player to rotate the Projector hologram

### ISSUE THREAD

**Issue by TheDeviantCrafter** [Flaxbeard/ImmersivePetroleum#29]
When using the Crusher Projector, the hologram is facing in a way that causes the finished multiblock's export hole to face west. I'd like it to face east, and it doesn't look like there's any way to rotate the hologram.

I'd prefer that the orientation of the hologram change based on the player's facing, allowing you to re-orient it if need be. Once you click on the ground to anchor it in place, though, it shouldn't move.

**Comment by KindarConrath** [comment]
while I agree that there is still some room for improvement, I feel I should let you know that you can rotate the projection with middle click & mirror it with Shift+Middle Click.  These are both configurable.

**Comment by Flaxbeard** [comment]
If you read the projector manual entry, you'd know that you can rotate it.
