### ISSUE TITLE
Distillation Tower doesn't output at all

### ISSUE THREAD

**Issue by angelnc1989** [Flaxbeard/ImmersivePetroleum#31]
Minecraft 1.10.2
Forge 12.18.3.2297
Immersive Engineering 0.10.60
Immersive Petroleum 1.0.5

Since the last update the Distillation Tower doesn't output Diesel to any pipe or tank and it can't be pumped out as well.
Output tested with IE Fluid Pipes, IE Fluid Pump, several Tanks, ExU Drums, ExU Transfer Nodes, RS Importer.
The RS External Storage can see the Diesel in the Distillation Tower, but can't extract it.

**Comment by bartczam** [comment]
I can confirm that bug, just tried it seconds ago.

**Comment by bartczam** [comment]
I just checked again - it DOES work only on one mirror position, the other does not work.
