### ISSUE TITLE
[Possible Idiot Question] Getting the fluid from the pumpjack

### ISSUE THREAD

**Issue by Techokami** [Flaxbeard/ImmersivePetroleum#32]
OKAY, so I am trying to get fluid from the pumpjack into some sort of storage container (in this case, a multiblock Tinker's Construct tank connected with Thermal Dynamics Super-Laminar Fluiducts). The pumpjack is in a chunk that has an oil resevoir, and it makes particles when it runs. BUT I am not getting any fluids out of the pumpjack. I have tried with and without servos on the outputs of the pumpjack. But even after running the setup for 24 HOURS while being chunkloaded... nothing in the tank.

What the hell am I doing wrong?

**Comment by Techokami** [comment]
Okay so you can only use Immersive Engineering's pipes. That's kind of silly.

**Comment by Flaxbeard** [comment]
It should work with all fluid handlers provided the siding is correct - I'll look into it

**Comment by eriniki** [comment]
I can confirm from my own testing in 1.11.2 that Thermal Dynamic pipes can't pull from the outputs either passively or actively, however ExU Drums and EnderStorage Ender Tanks placed directly against the outputs will fill up automatically - at least as a workaround in the meantime. :3 I assume all fluid inventories would work also, actually.

**Comment by Xiaminou** [comment]
It's still an issue in 1.12.2, Thermal Dynamics pipes will not get any fluid passively or actively.
Video for clarification: https://youtu.be/5FPYg5ndG8U
