### ISSUE TITLE
real oil reservoirs and minimal reservoirs are not distinguisable by texture

### ISSUE THREAD

**Issue by mindforger** [Flaxbeard/ImmersivePetroleum#35]
oil reservoirs and 3mb/t oil wells are not distringuishable from the textures, would be nice to be able to tell the difference

also the textures are quiet a bit too dominant, it is hard to determin the minerals in it soemtimes without using thew tooltip

oh god damn where are my manners .... the pumpjack ... the oil distillery ... they are soooooo coooooooolllll

**Comment by Flaxbeard** [comment]
Similar issue to #36 - trace wells shouldn't spawn naturally.

**Comment by mindforger** [comment]
Oh okay, got it.
