### ISSUE TITLE
Trace oil wells seem to be very common

### ISSUE THREAD

**Issue by BrisingrAerowing** [Flaxbeard/ImmersivePetroleum#36]
I have mapped out about 30 chunks, and all chunks that don't have some other thing in them (Mineral Vein or some kind of well) have a minimal oil well. I have found zero chunks that don't have anything.

IP: 1.0.6-1.10.2

**Comment by Flaxbeard** [comment]
This is unintended - unfortunately I'm not able to access a computer until Sunday when I'll try to fix this.
