### ISSUE TITLE
[1.12-1.0.9] Crash when the server starts

### ISSUE THREAD

**Issue by Zirrald** [Flaxbeard/ImmersivePetroleum#40]
[Crash-report](https://pastebin.com/GM3RhE94)

**Comment by winnetrie83** [comment]
I got the same crash on server start too

**Comment by frenzye** [comment]
same https://gist.github.com/frenzye/145c94bf537509c3fcc0fbf1f5f875f6

**Comment by Flaxbeard** [comment]
Fixed in 1.0.10 release - thank you for the bug report!
