### ISSUE TITLE
Forming the PumpJack, crashed the server

### ISSUE THREAD

**Issue by OldDogy** [Flaxbeard/ImmersivePetroleum#42]
Greetings,
A minute a go a friend tried to form the pumpjack and the whole server crashed.
Here is the pastebin of the crash-report. hope it helps, cheers!

https://pastebin.com/QCrbDTW6
-------------------------------------
Could have been because it was on the chunk edge.
this is what was left after the restart.
http://prntscr.com/fxj6yp

**Comment by Flaxbeard** [comment]
Should be fixed in 1.0.12
