### ISSUE TITLE
FPS drop when a machine is lubricated or when a gasoline generator is runing.

### ISSUE THREAD

**Issue by achman741** [Flaxbeard/ImmersivePetroleum#46]
After updating to version 1.1.0 on mc 1.10.2, i used the auto lubricator to lubricate a pumpjack and this caused a slight frame drop, also when i used the portable generator my fps drops to 15. Currently testing to see if its caused by any other mods in my instance.

**Comment by achman741** [comment]
Also found a rendering issue with pumpjacks when autolubricator is placed near them: http://imgur.com/a/SULB7    This occurs at strange angles.

**Comment by achman741** [comment]
with auto lubricator it appears to be a strange stuttering, it does drop my fps when uncapped from 300+ to 160-220.

**Comment by Flaxbeard** [comment]
Should be fixed in 1.1.2 - reopen if not
