### ISSUE TITLE
No Oil

### ISSUE THREAD

**Issue by eooxx** [Flaxbeard/ImmersivePetroleum#56]
The pumpjack pumps water instead of oil into the tank. What am I doing wrong? In version 1.10.2 and 1.11.2.

**Comment by Flaxbeard** [comment]
Are you in an oil chunk?

**Comment by eooxx** [comment]
Yes 

https://picload.org/view/rwdridda/2017-08-01_06.11.20.png.html
https://picload.org/view/rwdriddl/2017-08-01_06.11.32.png.html

**Comment by eooxx** [comment]
I have identified the problem, it is not a bug, I have to look at the coresample, whether it also displays oil graphically.

https://picload.org/view/rwdlddca/2017-08-02_21.04.12.png.html
