### ISSUE TITLE
Server crash changing dimensions

### ISSUE THREAD

**Issue by OrdinatorStouff** [Flaxbeard/ImmersivePetroleum#66]
[crash-2017-08-30_05.42.05-server.txt](https://github.com/Flaxbeard/ImmersivePetroleum/files/1262505/crash-2017-08-30_05.42.05-server.txt)

When coming back to overworld from Aroma's mining dim, the server crashed ticking world with Immersive Petroleum's onEntityJoiningWorld in the stack trace. This has happened more than once however does not happen EVERY time moving from one dim to next, so far I have not found a consistent or repeatable "pattern" to make it crash, though

**Comment by maruohon** [comment]
This happens when trying to unlock recipes for a FakePlayer, it crashes when trying to get the network handler for it to sync the recipe book to the client.
