### ISSUE TITLE
Can't rotate or reverse structure when holding projector

### ISSUE THREAD

**Issue by CNife** [Flaxbeard/ImmersivePetroleum#67]
In the Engineer's Manual I found how to rotate and reverse the structure shown by projector.
> Pressing the pick block button will rotate the structure, and sneaking while doing so will mirror it. Right clicking will lock the image in place, where it will show as long as the Projector is in your hotbar.

Immersive Petruleum version: 1.1.3
Mincraft version: 1.10.2
Forge version: 12.18.3.2422
Java version: 1.8.0_144

**Comment by SplitInfinitive** [comment]
you can find the "pick block" button in your controls.  Pressing it (provided there are no conflicts with that button) should let you rotate the structure
