### ISSUE TITLE
Boat Crash

### ISSUE THREAD

**Issue by MCRailRoader** [Flaxbeard/ImmersivePetroleum#70]
My game crashes when put a Motorboat into an Engineer's Workbench in immersivepetroleum-1.12-1.1.3

**Comment by LiEyWe** [comment]
Can confirm this.
Crash log: https://pastebin.com/NTHk9P6B

**Comment by minecrafterseppe** [comment]
i can confirm this PLEAS FIX  (version 1.12.2)

**Comment by minecrafterseppe** [comment]
can anybody even upgrade the motorboat?
if not whats a command to cheat in a fully upgrade one?

**Comment by LiEyWe** [comment]
looks like @Flaxbeard hasn't been active since August.

**Comment by minecrafterseppe** [comment]
i seriusly need that boat in ma life

**Comment by CplPibald** [comment]
It looks like the 1.12 IE API [has changed](https://github.com/BluSunrize/ImmersiveEngineering/commit/7a944ed6eb6db1ee2e78775e016e256a31dd321a#diff-b7254a06719fb826d931496092e8fb86L45), and IP needs to be updated to work with it.  I'm pretty sure this diff should fix the motorboat crash:

```
PS D:\src\ImmersivePetroleum> git diff
diff --git a/src/main/java/flaxbeard/immersivepetroleum/common/items/ItemIPUpgradableTool.java b/src/main/java/flaxbeard/immersivepetroleum/common/items/ItemIPUpgradableTool.java
index db9d4ae..5f0d765 100644
--- a/src/main/java/flaxbeard/immersivepetroleum/common/items/ItemIPUpgradableTool.java
+++ b/src/main/java/flaxbeard/immersivepetroleum/common/items/ItemIPUpgradableTool.java
@@ -80,5 +80,5 @@ public abstract class ItemIPUpgradableTool extends ItemIPInternalStorage impleme
        @Override
        public abstract boolean canModify(ItemStack stack);
        @Override
-       public abstract Slot[] getWorkbenchSlots(Container container, ItemStack stack, IInventory invItem);
+       public abstract Slot[] getWorkbenchSlots(Container container, ItemStack stack);
 }
\ No newline at end of file
diff --git a/src/main/java/flaxbeard/immersivepetroleum/common/items/ItemSpeedboat.java b/src/main/java/flaxbeard/immersivepetroleum/common/items/ItemSpeedboat.java
index e2a3d59..2e82bc6 100644
--- a/src/main/java/flaxbeard/immersivepetroleum/common/items/ItemSpeedboat.java
+++ b/src/main/java/flaxbeard/immersivepetroleum/common/items/ItemSpeedboat.java
@@ -25,6 +25,7 @@ import net.minecraft.world.World;
 import net.minecraftforge.fml.relauncher.Side;
 import net.minecraftforge.fml.relauncher.SideOnly;
+import net.minecraftforge.items.IItemHandler;
 import blusunrize.immersiveengineering.common.gui.IESlot;
 import blusunrize.immersiveengineering.common.util.ItemNBTHelper;
@@ -129,8 +130,9 @@ public class ItemSpeedboat extends ItemIPUpgradableTool
        }

        @Override
-       public Slot[] getWorkbenchSlots(Container container, ItemStack stack, IInventory invItem)
+       public Slot[] getWorkbenchSlots(Container container, ItemStack stack)
        {
+               IItemHandler invItem = stack.getCapability(CapabilityItemHandler.ITEM_HANDLER_CAPABILITY, null);
                return new Slot[]
                                {
                                        new IESlot.Upgrades(container, invItem, 0,  78, 35 - 5, "BOAT", stack, true),
```

I wasn't able to get IP to build (there was some weirdness with IE's `TileEntityMultiblockPart` class overriding the `pos` field inherited from `TileEntity` that prevented me from building), or I would've published a PR.

**Comment by Frontrider** [comment]
Where can I get my hands on a dev build of immersive engineering?

**Comment by Flaxbeard** [comment]
Expect an update fixing this today

**Comment by Frontrider** [comment]
We have quick fix, (a function which clears the boats from every player's inventory, and gives the materials back) but it would be great if we had a real solution :/.

**Comment by Flaxbeard** [comment]
Apologies for a bit of a delay, I was having some issues getting the IP development environment set up on my new machine - hopefully I can push something out this evening or by Friday at latest.

**Comment by Flaxbeard** [comment]
Fix is out - apologies for the wait!

**Comment by Frontrider** [comment]
Thank you! :) 🥇

**Comment by baronjutter** [comment]
Hi, I'm posting from the year 2019 and this problem seems to have come back.  Putting a motorboat on a work bench causes a client side crash.
