### ISSUE TITLE
Portable generator not outputting any power

### ISSUE THREAD

**Issue by Nerodon** [Flaxbeard/ImmersivePetroleum#72]
Using the following:
MC: 1.10.2
Forge: 12.18.3.2422
IE: 0.10-61
Immersive Petroleum: 1.10.2-1.1.3

Portable generators generate IF internally when given gasoline, they operate normally except IF does not transfer out to capacitors or machines. Tried using all types of connectors on all sides of the generator.

**Comment by Doragoon01** [comment]
I have had this problem for weeks and just figured it out.  Turns out I should have read the manual.  You don't need a connector on the generator.  An LV wire will connect directly to it.

**Comment by ExDomino** [comment]
I would prefered the need of a connector, because at this moment the wire is invisible when connecting to the Portable Generator.

**Comment by TheEvilEye05** [comment]
I have this problem too, but I'm even conecting the wire directly without the connector and it still doesn't generate any energy
