### ISSUE TITLE
[1.12] Is it possible to set oil to be infinite?

### ISSUE THREAD

**Issue by DeadSix27** [Flaxbeard/ImmersivePetroleum#75]
Basically wondering if I somehow could make oil simply last forever (and work in every chunk) at the cost of higher RF usage. 

Is there a way to do that? 

All i can find is max_mb_fluid, which doesn't describe a "-1" for unlimited or similar.

Closest I got is setting that to the highest possible and its weight to 100, while the rest is 0

**Comment by Techokami** [comment]
Technically, oil already lasts "forever". When a chunk's resevoir of oil reaches zero, you will still get oil, but only 3mB/tick. So... just leave your pumpjacks to run indefinitely?

**Comment by DeadSix27** [comment]
@Techokami can you configure the 3mb/tick rate so that it will continue at the normal rate? Then that's just what i want

**Comment by Techokami** [comment]
Yes. In the config file, under general, under machines, change `I:oil_replenish` to the desired value in mB.

**Comment by DeadSix27** [comment]
~~Are you sure that still exists in 1.12?~~
~~Looking at: https://github.com/Flaxbeard/ImmersivePetroleum/search?utf8=%E2%9C%93&q=oil_replenish&type=~~

Actually now that i know what to look for, in 1.12 its in the reservoirs list:
`# List of reservoir types. Format: name, fluid_name, min_mb_fluid, max_mb_fluid, mb_per_tick_replenish, weight, [dim_blacklist], [dim_whitelist], [biome_dict_blacklist], [biome_dict_whitelist]`

So  mb_per_tick_replenish would be the config value to change there.

**Comment by Techokami** [comment]
Sorry about that, I was looking at my config in 1.10.2; I didn't know it got changed in 1.12! (Relatedly, the 1.12 build on Curse should have its listing updated, because it works perfectly in 1.12.2)

**Comment by DeadSix27** [comment]
@Techokami Ye I#m using it in 1.12.2
