### ISSUE TITLE
[1.12.2][ver 1.1.5] Slippery effect crashes game and dupes held item.

### ISSUE THREAD

**Issue by deathaplenty** [Flaxbeard/ImmersivePetroleum#82]
### Description
The slippery effect will crash the game if the player is crouching around with the effect. When the player logs back in, his held item will be duplicated. 

I've had this happen by crouching around near lubricant placed in the world and by spraying myself with lubricant with the chem thrower. Crouch walking into lubricant was more consistent to crashing for me.

### How to reproduce
1. Place lubricant on the ground.
2. Crouch walk into it to get the slippery potion effect.

A crash should happen fairly quickly. When you open the game back up and open the world, you should find a copy of your held item in your inventory. 

### Crash report
https://pastebin.com/g3Uze6tJ

**Comment by Flaxbeard** [comment]
This is an Immersive Engineering bug, not an IP bug

**Comment by deathaplenty** [comment]
Oh gosh, I'm sorry. I'll post it there, then.

**Comment by Flaxbeard** [comment]
No problem, thanks for the report all the same!
