### ISSUE TITLE
Distillation Tower Multiblock not forming

### ISSUE THREAD

**Issue by akatosh100** [Flaxbeard/ImmersivePetroleum#89]
I set up the Distillation tower according to the projector. When I right click the redstone engineering block with an engineering hammer the structure doesn't form. Im currently on a MP server running FTB Revelation 1.2.0 on minecraft version 1.12.2.

**Comment by akatosh100** [comment]
Found out my issue was steel scaffolding slabs. There is no indication anywhere that steel scaffolding slabs are needed to form the platforms on the levels of the tower.

**Comment by Flaxbeard** [comment]
The Engineer's Manual and Projector both show the need for Steel Scaffolding slabs in the mod versions that require it

**Comment by akatosh100** [comment]
Oh really? Not seeing where it says "steel scaffolding slab". Also doesn't help that having the engineer's manual's open for more than 30 seconds crashes the game. 
![image](https://user-images.githubusercontent.com/25956698/34743798-ed7f5ad8-f53f-11e7-8165-00ef2917f814.png)

**Comment by calloatti** [comment]
The change was made in a recent version:

```
1.1.5

--------------------------------------- 

~ Distillation Tower now requires scaffolding slabs instead of full-block scaffolding
```

So the bug would be that the manual entry for required materials was not updated.
