### ISSUE TITLE
OFF TOPIC: Radioisotope thermoelectric generator

### ISSUE THREAD

**Issue by calloatti** [Flaxbeard/ImmersivePetroleum#9]
Since you created this add-on for IE, how about doing another one that adds nuclear power?

That is something that has been "planned" since forever and never implemented.

But instead of going the usual nuclear reactor/turbines route, how about a good old radioisotope thermoelectric generator? If we are going to pollute the land with oil and asphalt, we might as well throw some radiation into the mix!

Some links for reference:

https://en.wikipedia.org/wiki/Radioisotope_thermoelectric_generator
http://barentsobserver.com/en/arctic/2013/08/two-nuclear-generators-missing-arctic-26-08
http://bellona.org/news/nuclear-issues/radioactive-waste-and-spent-nuclear-fuel/2005-04-radioisotope-thermoelectric-generators-2
https://www.iaea.org/OurWork/ST/NE/NEFW/News/2012/repository/RTGs-Removed-Successfully-from-the-Baltic-Sea.html

Of course, nothing small. A large multiblock radioactive thing that outputs a lot of RF.

**Comment by Voxel-Friend** [comment]
Nuclear power is in active development now.
https://twitter.com/Damien_hazard/status/867363576650096640
https://twitter.com/Damien_hazard/status/867376345080369154
https://twitter.com/Damien_hazard/status/867390761725292544

**Comment by Flaxbeard** [comment]
I've considered going the other direction and adding some big [multiblock steam boilers](http://www.paxmanhistory.org.uk/images/BoilerShop1950s.jpg) and turbines to go with them as a low tech, early game alternative. I think I'll let Blu and Hazard handle the nuclear power.

**Comment by calloatti** [comment]
Great. May I interest you then in steam engine generators instead of the same old turbines? They look great:

https://www.google.com/search?q=horizontal+steam+engine+generator&tbm=isch
https://www.google.com/search?q=vertical+steam+engine+generator&tbm=isch
