### ISSUE TITLE
Server Crash : Invalid fluid name for reservoir 4

### ISSUE THREAD

**Issue by Tempest2113** [Flaxbeard/ImmersivePetroleum#91]
Minecraft : 1.12.2
Forge : 1.12.2-forge1.12.2-14.23.1.2587
Mod version :  immersivepetroleum-1.12.2-1.1.6.jar

No problem in Single Player
but Crash in Multi Player Forge Server

https://pastebin.com/gA2u0f3V

**Comment by Flaxbeard** [comment]
What's your config file look like?
