### ISSUE TITLE
[1.10.2] Crash while in Manual

### ISSUE THREAD

**Issue by ProxyPlayerHD** [Flaxbeard/ImmersivePetroleum#95]
[LOG](https://pastebin.com/2NDyaSiW)

The game kept repeating this while i looked at the Jumpjack pages, until it crashed after ~30 or so repeats of this error.
"[Client thread/ERROR]: Suppressed additional 21 model loading errors for domain immersiveengineering"

Versions:
Forge: 12.18.3.2511
IE: 0.10-61
IP: 1.1.3

**Comment by Euphoric** [comment]
Thats problem in JRE. Use newest Java runtime. https://github.com/BluSunrize/ImmersiveEngineering/issues/2225

**Comment by ProxyPlayerHD** [comment]
huh, java said nothing about an Update... need to check that.
